<?php

namespace AppBundle\Repository;

/**
 * DependantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependantRepository extends \Doctrine\ORM\EntityRepository
{
}
